### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by vinofilus** [destinydriven/cakephp-highcharts#25]
I'm fairly new to cakephp so I'm probably doing something very stupid, but I'm having trouble getting this into my project.
The /highcharts/highcharts_demo is working fine, so that's a good thing, but when I try to set up my own controller and view I get a blank space where the chart should be (html source shows the . Might you have some more detailed instructions on how to do that?
I do know that if I tell my ChartsController that it extends HighchartsAppController I get an error that the latter is not found. Is that a sign that I have a configuration issue elsewhere?
Thanks,
   Les...

**Comment by destinydriven** [comment]
Yes, it sounds like you're doing something terribly wrong. Take a look at the code examples eg minimalist controller to see how to set up your own controller to use Highcharts. You never have to extend your controller. What you want to do is include the Highcharts component.                                                                                                                                                                                                                                                                                                                                         With the spoon of determination in the hand of faith you can carve a tunnel of hope through the mountain of despair.                                                                                                                                                                                                                 From: LesKHSent: Tuesday, January 6, 2015 10:17 PMTo: destinydriven/cakephp-highcharts-pluginReply To: destinydriven/cakephp-highcharts-pluginSubject: [cakephp-highcharts-plugin] Installation troubles (#25)I'm fairly new to cakephp so I'm probably doing something very stupid, but I'm having trouble getting this into my project.
The /highcharts/highcharts_demo is working fine, so that's a good thing, but when I try to set up my own controller and view I get a blank space where the chart should be (html source shows the . Might you have some more detailed instructions on how to do that?
I do know that if I tell my ChartsController that it extends HighchartsAppController I get an error that the latter is not found. Is that a sign that I have a configuration issue elsewhere?
Thanks,
   Les...

—Reply to this email directly or view it on GitHub.

**Comment by vinofilus** [comment]
Since the demos work, I followed your comment and added:
public $components = array('Highcharts.Highcharts');
to my controller at the start. Then while troubleshooting I noticed that the minimalist controller extends HighchartsAppController, but as you note, that isn't necessary and doesn't work.
I've used the column function from the minimalist controller as the experiment in my own controller, and likewise used the minimalist column view. I can't figure out what is not loading. When I view the html source for the blank part of the html page, I see this, which looks promising to me:
<div class="chart">
        <h4>Column Chart</h4>

        <div id="columnwrapper" style="display: block; float: left; width:90%; margin-bottom: 20px;"></div>
        <div class="clear"></div>	

		<script type="text/javascript">
//<![CDATA[
$(document).ready(function() {
    // HIGHROLLER - HIGHCHARTS UTC OPTIONS 
    Highcharts.setOptions(
        {"global":{"useUTC":true}}
    );
    // HIGHROLLER - HIGHCHARTS 'Monthly Sales Summary' column chart

    var columnwrapper = new Highcharts.Chart(
        {"chart":{"renderTo":"columnwrapper","type":"column","width":1000,"height":750,"className":"skies"},"title":{"text":"Monthly Sales Summary"},"series":[{"name":"Example Online Store","id":null,"data":[7,6.9,9.5,14.5,18.2,21.5,25.2,26.5,23.3,18.3,13.9,9.6],"innerSize":null,"size":null}],"drilldown":{"series":{}},"subtitle":{"text":"Source: World Bank"},"xAxis":{"categories":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]},"labels":{"formatter":{"formatter":""}},"dataLabels":{"formatter":{"formatter":""}},"yAxis":{"style":{},"title":{"text":"Units"}},"credits":{"enabled":false}}
    );
    
    //for column drilldown
    function setChart(name, categories, data, color) {
        columnwrapper.xAxis[0].setCategories(categories);
        columnwrapper.series[0].remove();
        columnwrapper.addSeries({
            name: name,
            data: data,
            color: color || 'white'
        });
    }   
});
//]]>
</script>
