### ISSUE TITLE
HighChart Library not found.

### ISSUE THREAD

**Issue by bohrasankalp** [destinydriven/cakephp-highcharts#33]
I am finding the issue in console as 'ReferenceError: Highcharts is not defined'. Do I need to install highchart js externally? Is their any link? I already have Jquery included in my Layout. I am not using default layout provided by Plugin. I have all the steps as mentioned in Documents. The chart is preparing on the demo link. I have tested.

**Comment by destinydriven** [comment]
@bohrasankalp No, you do not have to install Highcharts externally. Take a closer look at how its used in the examples.  When you load the component, the helper is automatically loaded.  If you who code of your setup, I will be able to provide further assistance.

**Comment by bohrasankalp** [comment]
I have included library in same way as mentioned. Included in bootstrap and then included in '$component' array. Its loading well, but my console is giving me error of Highchart not defined. Because Hightchart JS is not loaded.

**Comment by destinydriven** [comment]
Can you check in view source on your page exactly what is being loaded?                                                                                                                                                                                                                                                                                                                                          With the spoon of determination in the hand of faith you can carve a tunnel of hope through the mountain of despair.                                                                                                                                                                                                                 From: bohrasankalpSent: Saturday, June 27, 2015 10:59 AMTo: destinydriven/cakephp-highchartsReply To: destinydriven/cakephp-highchartsCc: destinydrivenSubject: Re: [cakephp-highcharts] HighChart Library not found. (#33)I have included library in same way as mentioned. Included in bootstrap and then included in '$component' array. Its loading well, but my console is giving me error of Highchart not defined. Because Hightchart JS is not loaded.

—Reply to this email directly or view it on GitHub.

**Comment by bohrasankalp** [comment]
I am using 'jQuery version 1.10.2' along with 'jQuery migrate version 1.1.1'. My Highcharts JS is not loaded. I have checked the page source. At location of chart simple div is rendered along with javascript of Highchart function, which halts me with Highchart is not defined.

'
// HIGHROLLER - HIGHCHARTS UTC OPTIONS 
    Highcharts.setOptions( // Here is the error because its not fining library.
        {"global":{"useUTC":true}}
    );
    // HIGHROLLER - HIGHCHARTS 'Monthly Sales Summary' column chart
'

**Comment by bohrasankalp** [comment]
Its not loading helper automatically. I tried all the possible ways :(

**Comment by destinydriven** [comment]
It's quite possible that you may be missing something in your setup. I
can't tell for sure unless you share some code.  Let's take a look at your
controller setup, your page layout for your view page as well as the actual
page in which the chart will be rendered.

On Fri, Jul 3, 2015 at 7:48 AM, bohrasankalp <notifications@github.com>
wrote:

> Its not loading helper automatically. I tried all the possible ways :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/destinydriven/cakephp-highcharts/issues/33#issuecomment-118328206>
> .
>



-- 
With the spoon of determination in the hand of faith, you can carve a
tunnel of hope in the mountain of despair.

**Comment by bohrasankalp** [comment]
Simply what I follow is.
1. Added PLugin in Bootstrap file.
2. Added "Highcharts.Highcharts" my component variable. Thats it. expecting helper would be loaded itself.

This is what I done for setup. Yes, I won't deny if I use your layout then it render automatically without any patchup. but for my layout I have to add external JS file. because page source any sort of inclusion of javascript library. When I add library it worked.

**Comment by destinydriven** [comment]
So your issue has been resolved then?

On Fri, Jul 3, 2015 at 8:02 AM, bohrasankalp <notifications@github.com>
wrote:

> Simply what I follow is.
> 1. Added PLugin in Bootstrap file.
> 2. Added "Highcharts.Highcharts" my component variable. Thats it.
> expecting helper would be loaded itself.
>
> This is what I done for setup. Yes, I won't deny if I use your layout then
> it render automatically without any patchup. but for my layout I have to
> add external JS file. because page source any sort of inclusion of
> javascript library. When I add library it worked.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/destinydriven/cakephp-highcharts/issues/33#issuecomment-118329904>
> .
>



-- 
With the spoon of determination in the hand of faith, you can carve a
tunnel of hope in the mountain of despair.

**Comment by loopingGIT** [comment]
I have the same problem as @bohrasankalp, I am using boostrap with cake so i have another resources (css, js, etc) linked on my layout. Changing the order i add them to the layout fix this problem.

`
//I have to add this first

  	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">

  	
  	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  	<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

<?php
//and then add this ones.
    echo $this->Html->meta('icon');

    echo $this->fetch('meta');
    echo $this->fetch('css');
    echo $this->fetch('script');

    echo $this->Html->css('admin');
  ?>`
